site_name: C++ BBUnit
theme:
  name: 'material'
nav:
  - Home: index.md
  - Installation:
    - Include library: installation/include.md
  - Getting started:
    - First test: getting-started/first-test.md
  - Assertions:
    - List of assertions: assertions/list-assertions.md
  - Code structure: misc/structure.md