site_name: C++ BBUnit
theme:
  name: 'material'
nav:
  - Home: index.md
  - Installation:
    - Include as header file: installation/include.md
    - CMake's find_package: installation/find_package.md
  - Getting started:
    - First test: getting-started/first-test.md
  - Assertions:
    - List of assertions: assertions/list-assertions.md
    - Regular expressions: assertions/regex.md
    - Exceptions: assertions/exceptions.md
  - Code structure: misc/structure.md